### ISSUE TITLE
Tempmute and Mute commands in one

### ISSUE THREAD

**Issue by orestis119** [Shadow-Creation-Team/Protector#11]
Θα μπορούσατε να βάλετε και το mute και το tempmute command σε ένα command

:)

**Comment by antkarag13** [comment]
agree

**Comment by Tougrel** [comment]
@z7rwastaken is this possible? Something like `[p]mute <member> [time] <reason>` seems good to me! Add this to the To-Do list if you approve it ;)

**Comment by z7rwastaken** [comment]
Working on it.
