### ISSUE TITLE
[Enhancement] Punishment Logs alteration.

### ISSUE THREAD

**Issue by z7rwastaken** [Shadow-Creation-Team/Protector#17]
**Is your feature request related to a problem? Please describe.**
It isn't a problem at all, it's just a change in the embed of the punishment logs.

**Describe the solution you'd like**
![warn_example](https://user-images.githubusercontent.com/57574085/111083240-32526480-8515-11eb-9307-9d0bff0399dc.png)

**Describe alternatives you've considered**-

**Additional context**
Just looking better.

**Comment by Tougrel** [comment]
Looks awesome! You can also add a timestamp as a footer ;)
