### ISSUE TITLE
OAuth2 bug on production

### ISSUE THREAD

**Issue by vaggelismouras** [Shadow-Creation-Team/Protector#60]
When I am going to login with discord I am having an Invalid OAuth2 redirect_uri.

![image](https://github.com/AuraDevelopers/Aura/assets/166241107/0a7d2c18-da57-4c58-a2a9-dfa3d83c7c3d)

**Comment by tougrel** [comment]
We are aware of this and will post more info soon!

**Comment by tougrel** [comment]
Fixed in v2.2.4
