### ISSUE TITLE
Ban command bug

### ISSUE THREAD

**Issue by antkarag13** [Shadow-Creation-Team/Protector#9]
**Describe the bug**
When you are reply to someone with the mention on if you write `?ban reason test` the member is going to be banned. 

**Expected behavior**
I don't mention the user but the bot banned him.

**Screenshots**
![Screenshot_69](https://user-images.githubusercontent.com/71717457/110324912-48e15300-801f-11eb-961f-e21a845755c3.png)

**Comment by Tougrel** [comment]
This is a known issue with replies. This will be fixed and pushed on the next bug fix version! Thanks for the remind us tho ;)

Other commands with mentions also have the same problem. If you find them please report them! Thanks ;)
